import React from 'react';
import { Info, Target, Sparkles, BookOpen } from 'lucide-react';

interface GameWrapperProps {
  title: string;
  gameId: string;
  children: React.ReactNode;
}

const gameDescriptions: Record<string, { rules: string, lore: string, tips: string }> = {
  grid: {
    rules: "Grand Line Grid met à l'épreuve votre mémoire et votre connaissance des personnages du monde de One Piece. Le but du jeu est de remplir une grille de 9 cases en associant des personnages qui correspondent à deux critères spécifiques donnés (comme une faction, un équipage ou un Fruit du Démon). Chaque jour ou à chaque nouvelle partie, de nouvelles combinaisons vous sont proposées. Il vous faut sélectionner stratégiquement le bon pirate ou marine pour chaque intersection. Une erreur peut vous coûter cher en termes de score. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Tout comme Morgans qui collecte les informations du monde entier pour le World Economy News Paper, vous devrez fouiller dans vos souvenirs pour identifier chaque personnage. Le Nouveau Monde est un vaste océan où d'innombrables pirates, marines, et révolutionnaires s'affrontent. Connaître les alliances, les rangs, et les capacités de chacun est la clé de la survie. De East Blue à Erbaf, en passant par Wano et Egghead, le réseau des relations dans One Piece est l'un des plus denses de l'histoire du manga. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Privilégiez les personnages obscurs ! En effet, utiliser un personnage très connu comme Monkey D. Luffy ou Roronoa Zoro vous rapportera moins de points qu'un personnage de second plan si les critères le permettent. Soyez méticuleux et essayez de dénicher les pirates oubliés ou les agents du Cipher Pol les moins évidents pour faire exploser votre prime. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  tracker: {
    rules: "Le Log Pose Tracker vous invite à naviguer d'île en île en retrouvant le bon personnage selon des caractéristiques précises. Le jeu vous propose une série d'indices sur un personnage cible (âge, faction, fruit du démon, prime). À chaque proposition que vous faites, le Tracker vous indique si vous êtes sur la bonne voie à l'aide de flèches (plus grand, plus petit) et d'un code couleur pour valider chaque attribut. Vous avez un nombre limité d'essais pour trouver l'identité du personnage caché. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Sur Grand Line, il est impossible de naviguer avec une boussole normale. Seul le Log Pose permet de trouver son chemin d'une île à l'autre grâce aux champs magnétiques. De la même façon, ce mini-jeu vous demande de 'calibrer' votre boussole mémorielle. Les plus grands navigateurs comme Nami ou Bepo savent lire les signes subtils de la mer. Serez-vous capable de traquer n'importe quel individu sur les vastes mers du monde de One Piece ? Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Commencez toujours par un personnage moyen-âgeux avec une prime intermédiaire, comme Franky ou un vice-amiral. Cela vous permettra de diviser les possibilités par deux rapidement. Ne gaspillez pas vos premiers essais avec des personnages extrêmes (comme Gol D. Roger ou Chopper) à moins d'avoir des indices probants. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  duel: {
    rules: "Le Bounty Duel est un jeu de comparaison simple mais redoutablement efficace. Deux personnages s'affichent à l'écran, et vous devez deviner lequel des deux possède la prime la plus élevée (ou d'autres statistiques comme la taille ou l'âge si le mode de jeu varie). Enchaînez les bonnes réponses pour faire grimper votre propre prime. Si vous vous trompez, votre série est remise à zéro. Attention, certaines primes ont été gelées ou modifiées récemment ! Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Les primes (Bounty) sont au cœur de l'univers de One Piece. Elles ne reflètent pas seulement la force de combat d'un individu, mais surtout le niveau de menace qu'il représente pour le Gouvernement Mondial. Que ce soit les 5 564 800 000 Berrys de Gol D. Roger, ou la modeste première prime de 30 000 000 de Luffy, chaque affiche 'Wanted' raconte une histoire de destruction, d'idéaux et de rébellion. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Faites attention aux anciens grands corsaires (Shichibukai). Leurs primes ont été gelées pendant des années lorsqu'ils travaillaient pour le Gouvernement, puis ont soudainement explosé après la dissolution de leur ordre. Par exemple, Crocodile ou Boa Hancock ont des primes actuelles bien supérieures à leurs primes historiques ! Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  pyramid: {
    rules: "Le jeu de la Pyramide vous met au défi de construire une hiérarchie de personnages basée sur un critère précis, généralement la prime. Vous devez placer les personnages de la base vers le sommet, en veillant à ce que chaque étage supérieur possède une prime strictement plus élevée que l'étage en dessous. Si vous vous trompez dans l'ordre, l'édifice s'effondre et vous devrez recommencer. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "La structure du monde de One Piece est pyramidale. Au sommet trône Imu et le Conseil des Cinq Doyens, suivis par les Dragons Célestes, les Amiraux, les Vice-Amiraux, et ainsi de suite. Chez les pirates, c'est le système des Quatre Empereurs (Yonko) qui dicte la hiérarchie dans le Nouveau Monde, régnant sur de redoutables commandants et des flottes massives. Comprendre cette dynamique de pouvoir est essentiel pour survivre sur Grand Line. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Planifiez votre pyramide avant de placer le premier personnage. Identifiez d'abord celui qui a la prime la plus basse pour la base, et gardez jalousement le pirate à la prime colossale pour le sommet. Ne vous laissez pas tromper par la notoriété : certains personnages très forts ont des primes étonnamment basses parce qu'ils agissent dans l'ombre. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  pirateShadow: {
    rules: "L'ombre du pirate est un jeu visuel. Une silhouette noire (ou ombre) d'un personnage de One Piece apparaît à l'écran. Vous devez reconnaître de quel personnage il s'agit uniquement à partir de ses contours. Le jeu peut proposer des QCM ou vous demander de taper le nom. Plus vous répondez vite, plus votre score est élevé. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Dans le brouillard épais de Florian Triangle ou dans la pénombre des ruelles de Water Seven, il faut savoir identifier ses amis et ses ennemis au premier coup d'œil. Les silhouettes des personnages de One Piece sont volontairement dessinées par Eiichiro Oda pour être uniques et reconnaissables entre mille. Un chapeau de paille, un triple sabre, un nez allongé... chaque détail compte. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Concentre-vous sur les accessoires et les proportions physiques. Les armes (grandes épées, fusils), les chapeaux, ou les silhouettes disproportionnées (grands personnages comme Barbe Blanche ou Kuma) sont des indices cruciaux. Ne vous fiez pas seulement à la tête, analysez la pose globale de l'ombre. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  fusion: {
    rules: "Fusion Mystère vous présente une image générée qui mélange les traits du visage et les caractéristiques physiques de 2 ou 3 personnages de One Piece. Votre mission est de décomposer cette chimère visuelle et d'identifier correctement les personnages d'origine qui la composent. Sélectionnez les bons noms dans la liste pour résoudre l'énigme. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Si le Docteur Hogback de Thriller Bark ou Caesar Clown décidaient de créer l'hybride parfait, à quoi ressemblerait-il ? Dans un monde où les Fruits du Démon et la science du Germa 66 permettent de modifier les corps, l'apparence physique peut parfois être trompeuse. Saurez-vous reconnaître l'œil de Zoro croisé avec le sourire de Doflamingo et le chapeau de Law ? Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Découpez mentalement l'image en plusieurs parties : les yeux, la bouche, les cheveux, et les accessoires. Souvent, un trait très distinctif (comme les sourcils vrillés de Sanji ou la cicatrice de Luffy) est glissé subtilement pour vous mettre sur la piste. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  fourImages: {
    rules: "4 Pirates, 1 Mot s'inspire du célèbre jeu de mots. Quatre images vous sont présentées, et elles ont toutes un point commun lié à l'univers de One Piece (un lieu, une faction, un fruit du démon, un concept). À l'aide des lettres mélangées qui vous sont fournies, vous devez trouver le mot caché qui relie ces quatre illustrations. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "L'univers de One Piece est riche en symboliques, en factions et en mystères. Que ce soit la Volonté du D, les Poneglyphes, les Armes Antiques, ou les différentes formes de Haki, tout est connecté. Nicolas Robin serait excellente à ce jeu de déduction pour lier les indices historiques. À vous de prouver que vous êtes aussi perspicace que l'archéologue de l'équipage. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Si vous bloquez, essayez d'identifier précisément ce que représente chaque image séparément, puis cherchez le dénominateur commun. Les couleurs, les environnements ou les emblèmes (Jolly Roger) sont d'excellentes pistes. N'hésitez pas à utiliser vos jokers si les lettres proposées vous embrouillent. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  timeline: {
    rules: "La Chronologie Pirate vous demande de replacer des événements marquants de l'histoire de One Piece dans le bon ordre. Le jeu vous donne un événement initial, puis vous devez placer les événements suivants soit 'Avant', soit 'Après'. Constituez la frise chronologique la plus longue possible sans commettre d'erreur. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Depuis l'exécution du Roi des Pirates, Gol D. Roger, jusqu'aux événements d'Egghead, des décennies (et même des siècles avec le Siècle Oublié) d'histoire se chevauchent. La Grande Ère de la Piraterie a vu des alliances se forger et des empires s'effondrer. Maîtriser l'histoire, c'est comprendre les véritables enjeux qui lient Joy Boy, le Siècle Oublié et le trésor du One Piece. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Utilisez les ellipses temporelles comme points de repère majeurs (l'ellipse de 2 ans, l'ère de Roger). Mémorisez l'ordre des arcs narratifs (East Blue -> Alabasta -> Skypiea -> Enies Lobby -> Marineford -> Dressrosa -> Wano) pour placer facilement la plupart des événements liés à l'équipage du Chapeau de Paille. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  bountyTarget: {
    rules: "Dans Cible de Primes (Bounty Target), une prime cible est affichée à l'écran (ex: 500 000 000 ฿). Vous devez sélectionner, parmi un groupe de personnages, celui dont la prime exacte correspond au montant demandé. Le jeu teste votre précision chirurgicale sur les avis de recherche. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Les Chasseurs de Primes n'ont plus la cote dans le Nouveau Monde, mais les Marines et les Pirates surveillent de très près l'évolution des primes de leurs rivaux. Connaître la valeur exacte d'un homme permet d'estimer sa puissance et d'éviter les combats perdus d'avance. Êtes-vous un chasseur de primes assez aguerri pour connaître vos cibles sur le bout des doigts ? Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Attention aux évolutions de primes ! Souvenez-vous de la prime actuelle du personnage à la fin du dernier arc narratif. Les primes de l'équipage au chapeau de paille ont toutes augmenté massivement après l'arc du Pays des Wa (Wano). Un écart de quelques millions peut vous induire en erreur. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  alliances: {
    rules: "Alliances Secrètes vous teste sur les affiliations des personnages. Un personnage est affiché, et vous devez trouver à quel équipage, organisation ou faction il appartient parmi plusieurs propositions. De Baroque Works aux Minks, en passant par le SWORD ou le CP0, le réseau est complexe. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Dans One Piece, personne ne survit seul très longtemps. Les alliances forgent la puissance. Qu'il s'agisse de la Flotte de Chapeau de Paille, des alliances temporaires entre Supernovas (Kid, Law, Luffy) pour faire tomber des Empereurs, ou des manigances de Barbe Noire, le jeu des alliances est la clé du Nouveau Monde. Un allié d'hier peut être l'ennemi de demain. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Méfiez-vous des agents doubles ou des personnages qui ont changé de camp. Par exemple, Aokiji (Kuzan) faisait partie de la Marine mais s'est affilié à l'équipage de Barbe Noire. Lisez bien la question si le jeu précise une époque ou une fonction actuelle. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  undercover: {
    rules: "Mission Undercover est un jeu de déduction asymétrique. Chaque joueur (ou l'IA) reçoit un mot secret lié à One Piece, sauf un joueur (l'infiltré) qui reçoit un mot très similaire (ex: 'Merry' vs 'Sunny'). Tour à tour, chaque joueur doit décrire son mot avec un seul mot-indice. Le but des marins est de démasquer l'infiltré. L'infiltré doit deviner le mot principal pour gagner. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "L'infiltration est une spécialité redoutable dans le monde de One Piece. Le Cipher Pol (CP9, CP0) s'est infiltré pendant des années à Water Seven, X Drake travaillait secrètement pour le SWORD au sein de l'équipage de Kaido, et Corazon trompait Doflamingo pour sauver Law. Sauriez-vous cacher votre véritable allégeance lors d'un interrogatoire ? Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Si vous êtes un joueur normal, donnez un indice suffisamment clair pour que les autres vous identifient comme un allié, mais assez vague pour ne pas donner le mot exact à l'infiltré. Si vous êtes l'infiltré, écoutez bien les autres, restez flou, et essayez de déduire le mot principal avant de vous faire attraper. Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  },
  crossword: {
    rules: "Mots Croisés vous plonge dans des grilles classiques de mots croisés, mais entièrement thématiques One Piece. Lisez les définitions (horizontales et verticales) et remplissez la grille avec des noms d'îles, de personnages, d'attaques ou de Fruits du Démon. Remplir la grille vous rapporte une grosse prime. Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.",
    lore: "Pour percer les mystères des Poneglyphes, il faut de la patience, de l'érudition et une logique à toute épreuve. Tout comme les érudits d'Ohara, ce jeu vous demande de mobiliser l'ensemble de votre savoir encyclopédique sur l'univers d'Eiichiro Oda. Un vrai test de connaissance pour les fans hardcores. Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.",
    tips: "Commencez par les mots courts (3 ou 4 lettres) ou les noms très connus. Vérifiez toujours les intersections : elles sont vos meilleurs alliés pour confirmer une hypothèse douteuse. Certaines définitions peuvent être des citations célèbres ou des rires de personnages ('Zehahaha'). Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire."
  }
};

export default function GameWrapper({ title, gameId, children }: GameWrapperProps) {
  const content = gameDescriptions[gameId] || { rules: "Jouez au jeu ! Les règles ont été soigneusement équilibrées pour offrir un défi croissant. Les premières étapes peuvent sembler abordables, mais la difficulté s'accentue rapidement à mesure que vous progressez. Vous devrez faire preuve d'une grande capacité d'adaptation, mémoriser vos erreurs passées et analyser minutieusement les données fournies à l'écran. Ne vous précipitez pas : chaque action a des conséquences sur votre score et votre progression globale. Si vous échouez, prenez le temps de revoir vos classiques, de consulter l'encyclopédie et de comprendre pourquoi telle ou telle option était la bonne. C'est un test d'endurance autant que de connaissances.", lore: "Découvrez l'univers Ce mini-jeu ne se contente pas d'être un simple passe-temps, il s'inscrit dans la grande tradition des mystères de l'univers d'Eiichiro Oda, où chaque détail, chaque visage et chaque alliance raconte une histoire qui dépasse l'entendement. Depuis la mer bleue de l'Est jusqu'aux confins tumultueux du Nouveau Monde, l'histoire des pirates s'écrit avec le sang, les rêves et la volonté héritée. Les Poneglyphes anciens résonnent encore avec les secrets d'un siècle oublié, tandis que la Marine et le Gouvernement Mondial tentent par tous les moyens de cacher la véritable histoire. C'est dans ce monde riche et complexe que s'ancrent nos mécaniques de jeu. En maîtrisant ces informations, vous ne faites pas que jouer, vous devenez un véritable érudit de l'univers de One Piece, capable de déjouer les plans de la Marine, de déchiffrer les complots des Empereurs, et de vous hisser au sommet de la hiérarchie mondiale.", tips: "Amusez-vous bien Un joueur averti en vaut deux. Pensez toujours à sortir des sentiers battus et à ne pas vous fier aux réponses qui semblent trop évidentes. Les développeurs ont parfois glissé des pièges subtils basés sur des arcs très anciens ou des personnages secondaires apparus dans des chapitres annexes (cover stories). N'hésitez pas à jouer à plusieurs ou à débattre avec d'autres fans pour croiser vos connaissances, car personne ne peut se vanter de connaître One Piece à 100% du premier coup. Enfin, la persévérance est la clé. L'entraînement régulier sur ce jeu affinera vos réflexes et votre mémoire." };

  return (
    <div className="space-y-10 animate-in fade-in duration-500 pb-10">
      
      {/* HEADER SECTION */}
      <div className="bg-gradient-to-br from-[#0B0D1E] to-[#15193B] border border-violet-500/20 rounded-3xl p-6 md:p-10 shadow-2xl relative overflow-hidden">
        <div className="absolute top-0 right-0 w-[400px] h-[400px] bg-violet-600/10 rounded-full blur-[100px] pointer-events-none" />
        <div className="relative z-10 flex flex-col md:flex-row items-start md:items-center justify-between gap-6">
          <div className="space-y-4 max-w-3xl">
            <span className="inline-block px-3 py-1 rounded-full bg-violet-900/40 text-violet-300 text-xs font-mono font-bold tracking-widest border border-violet-500/30">
              MINI-JEU GRAND LINE
            </span>
            <h1 className="text-3xl md:text-5xl font-heading font-black text-transparent bg-clip-text bg-gradient-to-r from-amber-400 via-amber-200 to-white uppercase tracking-tighter">
              {title}
            </h1>
            <p className="text-slate-300 text-sm md:text-base leading-relaxed max-w-2xl">
              Plongez dans l'univers de One Piece avec ce défi interactif. Testez vos connaissances, accumulez des Berrys et grimpez dans le classement mondial des primes.
            </p>
          </div>
        </div>
      </div>

      {/* GAME INTERACTIVE SECTION */}
      <div className="w-full relative z-20">
        <div className="p-1 rounded-3xl bg-gradient-to-b from-violet-500/20 to-transparent">
          <div className="bg-[#0A0C1C] rounded-[22px] overflow-hidden shadow-2xl">
            {children}
          </div>
        </div>
      </div>

      {/* SEO & LORE DESCRIPTION SECTION */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-[#11142A]/80 border border-white/5 rounded-2xl p-6 md:p-8 space-y-4 shadow-lg backdrop-blur-sm">
          <div className="flex items-center gap-3 text-amber-400 mb-2">
            <BookOpen className="w-6 h-6" />
            <h3 className="font-heading font-black text-xl uppercase tracking-wider">Règles du jeu</h3>
          </div>
          <p className="text-slate-300 text-sm leading-relaxed text-justify">
            {content.rules}
          </p>
        </div>

        <div className="bg-[#11142A]/80 border border-white/5 rounded-2xl p-6 md:p-8 space-y-4 shadow-lg backdrop-blur-sm">
          <div className="flex items-center gap-3 text-violet-400 mb-2">
            <Target className="w-6 h-6" />
            <h3 className="font-heading font-black text-xl uppercase tracking-wider">L'Univers</h3>
          </div>
          <p className="text-slate-300 text-sm leading-relaxed text-justify">
            {content.lore}
          </p>
        </div>

        <div className="bg-[#11142A]/80 border border-white/5 rounded-2xl p-6 md:p-8 space-y-4 shadow-lg backdrop-blur-sm">
          <div className="flex items-center gap-3 text-emerald-400 mb-2">
            <Sparkles className="w-6 h-6" />
            <h3 className="font-heading font-black text-xl uppercase tracking-wider">Astuces</h3>
          </div>
          <p className="text-slate-300 text-sm leading-relaxed text-justify">
            {content.tips}
          </p>
        </div>
      </div>

    </div>
  );
}
